export function generateFallbackSchemaAnalysis(schemaStr: string): any {
  let paths: { path: string, method: string }[] = [];
  try {
    const s = JSON.parse(schemaStr);
    if (s.paths) {
      paths = Object.keys(s.paths).map(p => ({ path: p, method: Object.keys(s.paths[p])[0] || 'get' }));
    }
  } catch (e) {
    paths = [{ path: '/api/v1/resource', method: 'get' }];
  }
  if (paths.length === 0) paths = [{ path: '/api/v1/users', method: 'post' }];

  return {
    endpoints: paths.map(p => ({
      path: p.path,
      method: p.method,
      testCases: [
        {
          title: `Valid ${p.method.toUpperCase()} request to ${p.path}`,
          type: 'positive',
          payload: p.method.toLowerCase() !== 'get' ? { data: 'valid' } : {}
        },
        {
          title: `Missing required fields for ${p.method.toUpperCase()} ${p.path}`,
          type: 'negative',
          payload: p.method.toLowerCase() !== 'get' ? {} : { invalid_query: true }
        },
        {
          title: `SQL Injection attack on ${p.path}`,
          type: 'security',
          payload: { query: "' OR 1=1 --" }
        }
      ]
    }))
  };
}

export function generateFallbackMockServer(prompt: string): any {
  return {
    endpoints: [
      {
        path: "/api/mock/users",
        method: "GET",
        delay: 500,
        status: 200,
        headers: { "Content-Type": "application/json" },
        responseBody: [
          { id: 1, name: "Alice", role: "admin" },
          { id: 2, name: "Bob", role: "user" }
        ]
      },
      {
        path: "/api/mock/health",
        method: "GET",
        delay: 100,
        status: 200,
        headers: { "Content-Type": "application/json" },
        responseBody: { status: "ok" }
      }
    ]
  };
}

export function generateFallbackSecurityMitigation(finding: string): any {
  return {
    mitigations: [
      {
        title: "Input Validation & Sanitization",
        description: "Always validate and sanitize user input on the server side.",
        codeSnippet: "// Implement strict validation logic here\\nconst isValid = validate(input);",
        complexity: "Medium"
      }
    ],
    explanation: "Generated by local fallback engine because AI service was unavailable.",
    priority: "High"
  };
}

export function generateFallbackAltText(html: string): any {
  return {
    elements: [
      {
        selector: "img",
        suggestedAlt: "Image description provided by fallback",
        reason: "Fallback generator triggered"
      }
    ]
  };
}

export function generateFallbackTestHealing(errorMsg: string): any {
  return {
    diagnosis: "The test failed likely due to a locator change or a timeout. (Fallback Diagnosis)",
    fixedCode: "// Original test code couldn't be healed via AI.\\n// Please manually update the locator.\\nawait page.locator('update-me').click();",
    confidence: "Low"
  };
}

export function generateFallbackContractValidation(): any {
  return {
    isValid: true,
    violations: [],
    coverage: 100,
    recommendations: ["AI contract validation unavailable. Assuming contract is valid (Fallback)."]
  };
}

