import type { IFormatter } from "./formatter.interface";
import type { ExportOptions } from "../export.types";
import type { SqlDialect } from "@/core/types/common";

export class SqlFormatter implements IFormatter {
  mimeType = "application/sql";
  fileExtension = ".sql";
  encoding = "utf-8" as const;

  format(data: Record<string, unknown>[], options: Partial<ExportOptions>): string {
    if (data.length === 0) return "-- No data to export";

    const tableName = options.tableName ?? "test_data";
    const dialect = options.dialect ?? "mysql";
    const includeCreate = options.includeCreate !== false;
    const includeDropIfExists = options.includeDropIfExists === true;

    const allKeys = this.extractAllKeys(data);
    const lines: string[] = [];

    lines.push(`-- Generated by QA Data Studio`);
    lines.push(`-- ${new Date().toISOString()}`);
    lines.push("");

    if (includeDropIfExists) {
      lines.push(`DROP TABLE IF EXISTS ${this.quoteIdentifier(tableName, dialect)};`);
      lines.push("");
    }

    if (includeCreate) {
      lines.push(this.generateCreateTable(tableName, allKeys, data, dialect));
      lines.push("");
    }

    for (const record of data) {
      lines.push(this.generateInsert(tableName, allKeys, record, dialect));
    }

    return lines.join("\n");
  }

  private extractAllKeys(data: Record<string, unknown>[]): string[] {
    const keySet = new Set<string>();
    for (const record of data) {
      for (const key of Object.keys(record)) {
        keySet.add(key);
      }
    }
    return Array.from(keySet);
  }

  private inferSqlType(key: string, data: Record<string, unknown>[], dialect: SqlDialect): string {
    for (const record of data) {
      const value = record[key];
      if (value === null || value === undefined) continue;

      if (typeof value === "number") {
        return Number.isInteger(value) ? "INTEGER" : "DECIMAL(15,2)";
      }
      if (typeof value === "boolean") {
        return dialect === "postgres" ? "BOOLEAN" : "TINYINT(1)";
      }
      if (typeof value === "string") {
        if (value.length > 255) {
          return dialect === "mysql" ? "TEXT" : "TEXT";
        }
        return "VARCHAR(255)";
      }
      if (typeof value === "object") {
        return dialect === "postgres" ? "JSONB" : "JSON";
      }
    }
    return "VARCHAR(255)";
  }

  private generateCreateTable(
    tableName: string,
    keys: string[],
    data: Record<string, unknown>[],
    dialect: SqlDialect
  ): string {
    const quotedTable = this.quoteIdentifier(tableName, dialect);
    const columns = keys.map((key) => {
      const sqlType = this.inferSqlType(key, data, dialect);
      return `  ${this.quoteIdentifier(key, dialect)} ${sqlType}`;
    });

    return `CREATE TABLE ${quotedTable} (\n${columns.join(",\n")}\n);`;
  }

  private generateInsert(
    tableName: string,
    keys: string[],
    record: Record<string, unknown>,
    dialect: SqlDialect
  ): string {
    const quotedTable = this.quoteIdentifier(tableName, dialect);
    const columns = keys.map((k) => this.quoteIdentifier(k, dialect)).join(", ");
    const values = keys.map((k) => this.formatSqlValue(record[k])).join(", ");

    return `INSERT INTO ${quotedTable} (${columns}) VALUES (${values});`;
  }

  private quoteIdentifier(name: string, dialect: SqlDialect): string {
    if (dialect === "mysql") return `\`${name}\``;
    return `"${name}"`;
  }

  private formatSqlValue(value: unknown): string {
    if (value === null || value === undefined) return "NULL";
    if (typeof value === "number") return String(value);
    if (typeof value === "boolean") return value ? "1" : "0";
    if (typeof value === "object") {
      return `'${this.escapeSqlString(JSON.stringify(value))}'`;
    }
    return `'${this.escapeSqlString(String(value))}'`;
  }

  private escapeSqlString(str: string): string {
    return str.replace(/'/g, "''");
  }
}
